[chipflow]
project_name = "chipflow-examples"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.steps]
board = "design.steps.board:MyBoardStep"
software = "design.steps.software:MySoftwareStep"

[chipflow.silicon]
process = "ihp_sg13g2"
package = "pga144"

[chipflow.silicon.pads]
# System
sys_clk   = { type = "clock", loc = "114" }
sys_rst_n = { type = "reset", loc = "115" }
