[chipflow]
project_name = "chipflow-examples"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.steps]
board = "design.steps.board:MyBoardStep"

[chipflow.silicon]
process = "ihp_sg13g2"
package = "pga144"
